name: freo_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^4.0.0
  connectivity_plus: ^1.0.3
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.2
  dio_http_cache: ^0.3.0
  dio_cache_interceptor: ^3.4.2
  shared_preferences: ^2.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

